# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_recordingSuite_New():
    '''windmill firefox Mockup_url
    '''
    client = WindmillTestClient(__name__)

    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[1]/h3", validator=u'42 Coffee Cups Test Assignment')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[2]/pre", validator=u'Name')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[3]/pre", validator=u'Last name')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[10]/pre", validator=u'Date of birth')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[9]/pre", validator=u'Bio')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[4]/pre", validator=u'Contacts')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[6]", validator=u'Jabber')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[7]", validator=u'Skype')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[8]", validator=u'Other contacts')
    client.asserts.assertTextIn(xpath=u"//div[@id='WORKSHEET']/div[8]/pre", validator=u'Other contacts')